// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: goods.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGood = `-- name: CreateGood :one
INSERT INTO goods (name, category_id, price, description, weight) VALUES ($1, $2, $3, $4,$5) RETURNING id
`

type CreateGoodParams struct {
	Name        string
	CategoryID  int32
	Price       pgtype.Numeric
	Description string
	Weight      pgtype.Numeric
}

func (q *Queries) CreateGood(ctx context.Context, arg CreateGoodParams) (int32, error) {
	row := q.db.QueryRow(ctx, createGood,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.Description,
		arg.Weight,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
