// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32
	Name string
}

type Good struct {
	ID          int32
	Name        string
	CategoryID  int32
	Price       pgtype.Numeric
	Description string
	Weight      pgtype.Numeric
}

type GoodsOrder struct {
	GoodID  int32
	OrderID int32
}

type Order struct {
	OrderID          int32
	UserID           int32
	OrderDescription pgtype.Text
	OrderType        string
	StateID          int32
	PriorityID       int32
	GoodsIds         string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type OrderPriorite struct {
	PriorityID int32
	Priority   string
}

type OrderState struct {
	StateID   int32
	StateName string
}

type Payment struct {
	PaymentID     int32
	OrderID       int32
	PaymentSystem pgtype.Text
	Amount        pgtype.Numeric
	Status        string
	PaidAt        pgtype.Timestamp
}

type User struct {
	UserID       int32
	Username     string
	PasswordHash string
	Email        pgtype.Text
	Role         string
	CreatedAt    pgtype.Timestamp
}
